# Generated by Django 5.0.3 on 2024-04-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_requisition_created_at_alter_requisition_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('place', models.CharField(max_length=200)),
                ('requisition', models.BooleanField(default=False)),
                ('completion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.requisition')),
            ],
        ),
    ]
