# Generated by Django 5.0.3 on 2024-04-01 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_requisition_created_at_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.DateTimeField(null=True),
        ),
    ]
