# Generated by Django 5.0.3 on 2024-04-01 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_schedule_driver_id_schedule_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='requisition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.requisition'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle'),
        ),
    ]
