# Generated by Django 5.0.3 on 2024-04-01 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_schedule_arrival_time_alter_schedule_driver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='requisition_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.requisition'),
        ),
    ]
