# Generated by Django 5.0.3 on 2024-04-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_schedule_requisition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
