# Generated by Django 5.0.3 on 2024-04-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_requisition_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle'),
        ),
    ]
