# Generated by Django 5.0.3 on 2024-04-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_schedule_driver_id_alter_schedule_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='arrival_time',
            field=models.DateTimeField(null=True),
        ),
    ]
